management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false
    
spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      
  application:
    name: demo-app
    
test.property: test1
